name: Update chains in cosmos.config.json
on:
  push:
  pull_request:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Dependencies
        run: npm install
      - name: Run app.js
        run: npm start    
      - name: Commit the new cosmos.config.json file
        run: |-
          git diff
          git config --global user.email "contact.atmoner@gmail.com"
          git config --global user.name "atmoner"
          git diff --quiet || (git add cosmos.config.json && git commit -m "Update the cosmos.config.json file")
          git push origin main
